<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageType>Template</PackageType>
    <PackageId>VueWebEnterpriseSQL.Template</PackageId>
    <Title>Vue Web Enterprise Architecture Template (SQL Server)</Title>
    <Authors>Mark Couvaras</Authors>
    <Description>A .NET template for Vue Web Enterprise clean architecture projects using MS SQL Server.</Description>
    <TargetFramework>net10.0</TargetFramework>
    <IncludeContentInPack>true</IncludeContentInPack>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <ContentTargetFolders>content</ContentTargetFolders>
    <NoDefaultExcludes>true</NoDefaultExcludes>
    <NoWarn>$(NoWarn);NU5128</NoWarn>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="**/*" Exclude="MyTemplatePack.csproj;**/bin/**;**/obj/**;**/.vs/**;**/.git/**;**/.github/**;**/.gitignore;**/.gitattributes" />
    <Compile Remove="**/*" />
  </ItemGroup>

</Project>
